-- -> CREATE TABLE COUNTRY
CREATE TABLE IF NOT EXISTS Country(
      Id     INTEGER AUTOINCREMENT
    , Name   TEXT NOT NULL
    , Alpha2 TEXT NOT NULL
    , CONSTRAINT PK_Country_Id PRIMARY KEY (Id)
);
-- <- CREATE TABLE COUNTRY
